### PR TITLE
Add SCIM 2.0 Compliance Test Suite 

### PR DESCRIPTION
**Pull request by Vindulamj**

### CODE REVIEW

**Comment by darshanasbg** [comment]
@Vindulamj,

I tried build this locally and it failed with following error. Please check and update the PR..

```
Downloaded: http://maven.wso2.org/nexus/content/groups/wso2-public/org/apache/pdfbox/pdfbox/2.0.7/pdfbox-2.0.7.jar (2414 KB at 179.8 KB/sec)
Downloading: http://maven.wso2.org/nexus/content/repositories/releases/info/simplecloud/scimcore/0.1/scimcore-0.1.jar
Downloading: https://repo.maven.apache.org/maven2/info/simplecloud/scimcore/0.1/scimcore-0.1.jar
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 36.659 s
[INFO] Finished at: 2017-07-29T00:11:07+05:30
[INFO] Final Memory: 10M/150M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project compliance: Could not resolve dependencies for project info.simplecloud.scimproxy:compliance:war:0.1: Could not find artifact info.simplecloud:scimcore:jar:0.1 in project.local (file:/Users/darshanagunawardana/Documents/rnd/source/scim2-compliance-test-suite/repo) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
```

Thanks,

**Comment by Vindulamj** [comment]
@darshanasbg 

The build failure had occurred as scimcore-0.1.jar was not available in scim2-compliance-test-suite/repo/ location. This had not been pushed as the gitignore forces it to be ignored. This jar is an essential part of SCIM 1.1 test and hence it is necessary to be in the repo (This has nothing to do with the SCIM 2.0 Test suite). Therefore I changed the gitignore to accommodate jar files and updated the PR.

Thanks

**Comment by darshanasbg** [comment]
@Vindulamj 

Thanks Vindula, now its builds when I point to maven repo which added in https://github.com/wso2-incubator/scim2-compliance-test-suite/pull/1/commits/989cc026d072eabce9fa9aecae2e20d819c8d46b.. But this has to be solved in other way.. @omindu and myself will check on other options.

**Comment by darshanasbg** [comment]
@Vindulamj meanwhile can you update the licence headers of the relevant files.

**Comment by Vindulamj** [comment]
@darshanasbg 

I Updated the license headers of the relevant files.

**Comment by darshanasbg** [comment]
Thanks @Vindulamj, but license year seems to be incorrect too.. Can you please fix that..

**Comment by Vindulamj** [comment]
@darshanasbg  Fixed it.

**Review by omindu — APPROVED** [review]

**Pull request merged**
